apiVersion: v1
kind: ConfigMap
metadata:
  name: envvar-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "superset.name" . }}
    chart: {{ template "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PG_USER: ""
  PG_PASS: ""
  PG_HOST: ""
  PORTAL_HOST: ""
  PORTAL_API_HOST: ""
  PORTAL_API_KEY: ""
  ANALYTICS_API_KEY: ""
  ANALYTICS_API_HOST: ""